<%! import onlinejudge_template.generator.cplusplus as cplusplus %>\
<%
    data['config']['indent'] = '\t'
    data['config']['scanner'] = 'scanf'
    data['config']['printer'] = 'printf'
%>\
#include <cstdio>
#include <string>
#include <vector>

${cplusplus.declare_constants(data)}
${cplusplus.return_type(data)} solve(${cplusplus.formal_arguments(data)}) {
	// TODO: edit here
}

// generated by online-judge-template-generator (https://github.com/kmyk/online-judge-template-generator)
int main() {
${cplusplus.read_input(data)}
	auto ${cplusplus.return_value(data)} = solve(${cplusplus.actual_arguments(data)});
${cplusplus.write_output(data)}
	return 0;
}
