<%!
    import onlinejudge_template.generator.python as python
    import onlinejudge_template.generator.about as about
%>\
#!/usr/bin/env python3
# usage: $ oj generate-input 'python3 generate.py'
import random

# generated by ${about.title} ${about.version} (${about.url})
def main():
${python.generate_input(data)}
${python.write_input(data)}

if __name__ == "__main__":
    main()
