<%!
    import onlinejudge_template.generator.python as python
    import onlinejudge_template.generator.about as about
%>\
#!/usr/bin/env python3
# from typing import *

${python.declare_constants(data)}

# def solve(${python.formal_arguments(data)}) -> ${python.return_type(data)}:
def solve(${python.formal_arguments(data, typed=False)}):
    pass  # TODO: edit here

# generated by ${about.title} ${about.version} (${about.url})
def main():
${python.read_input(data)}
    ${python.return_value(data)} = solve(${python.actual_arguments(data)})
${python.write_output(data)}

if __name__ == '__main__':
    main()
