<%! import onlinejudge_template.generator.python as python %>\
#!/usr/bin/env python3
# from typing import *

# def solve(${python.formal_arguments(data)}) -> ${python.return_type(data)}:
def solve(${python.formal_arguments(data, typed=False)}):
    pass  # TODO: edit here

# generated by online-judge-template-generator (https://github.com/kmyk/online-judge-template-generator)
def main():
${python.read_input(data)}
    ${python.return_value(data)} = solve(${python.actual_arguments(data)})
${python.write_output(data)}

if __name__ == '__main__':
    main()
