<%! import onlinejudge_template.generator.cplusplus as cplusplus %>\
<%
    data['config']['rep_macro'] = 'REP'
%>\
#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++ (i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++ (i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; -- (i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); -- (i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;

${cplusplus.return_type(data)} solve(${cplusplus.arguments_types(data)}) {
    // TODO: edit here
}

// generated by online-judge-template-generator (https://github.com/kmyk/online-judge-template-generator)
int main() {
${cplusplus.read_input(data)}
    auto ${cplusplus.return_values(data)} = solve(${cplusplus.arguments(data)});
${cplusplus.write_output(data)}
    return 0;
}
