#!/usr/bin/env python3

def solve(n, a):  # TODO: edit here
    return -1  # TODO: edit here

# NOTE: template.py is a work in progress
# generated by online-judge-template-generator (https://github.com/kmyk/online-judge-template-generator)
def main():
    n = int(input())  # TODO: edit here
    a = list(map(int, input().split()))  # TODO: edit here
    print(solve(n, a))  # TODO: edit here

if __name__ == '__main__':
    main()
