<%! import onlinejudge_template.generator.python as python %>\
#!/usr/bin/env python3
# from typing import *

# def solve(${python.formal_arguments(data)}) -> ${python.return_type(data)}:
def solve(${python.actual_arguments(data)}):
    # TODO: edit here
    return ${python.return_values(data)}

# generated by online-judge-template-generator (https://github.com/kmyk/online-judge-template-generator)
def main():
${python.read_input(data)}
    ${python.return_values(data)} = solve(${python.actual_arguments(data)})
${python.write_output(data)}

if __name__ == '__main__':
    main()
